const songs = [
    { id: "after-dark", title: "After Dark", artist: "Mr.Kitty", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/after-dark.mp3" },
    { id: "akhmedov-kamali-slowed", title: "Akhmedov Kamali (Slowed)", artist: "Akhmedov", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/akhmedov-kamali-slowed.mp3" },
    { id: "all-i-want-is-you", title: "All I Want Is You", artist: "Miguel", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/all-i-want-is-you.mp3" },
    { id: "alors-on-danse", title: "Alors on danse", artist: "Stromae", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/alors-on-danse.mp3" },
    { id: "as-it-was", title: "As It Was", artist: "Harry Styles", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/as-it-was.mp3" },
    { id: "baby", title: "Baby", artist: "Justin Bieber", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/baby.mp3" },
    { id: "babydoll", title: "Babydoll", artist: "Ari Abdul", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/babydoll.mp3" },
    { id: "back-to-friends", title: "Back to Friends", artist: "sombr", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/back-to-friends.mp3" },
    { id: "bananza-belly-dancer", title: "Bananza (Belly Dancer)", artist: "Akon", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/bananza-belly-dancer.mp3" },
    { id: "careless-whisper", title: "Careless Whisper", artist: "George Michael", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/careless-whisper.mp3" },
    { id: "cheri-cheri-lady", title: "Cheri Cheri Lady", artist: "Modern Talking", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/cheri-cheri-lady.mp3" },
    { id: "come-and-get-your-love", title: "Come and Get Your Love", artist: "Redbone", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/come-and-get-your-love.mp3" },
    { id: "copines", title: "Copines", artist: "Aya Nakamura", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/copines.mp3" },
    { id: "counting-stars", title: "Counting Stars", artist: "OneRepublic", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/counting-stars.mp3" },
    { id: "dai-dai", title: "Dai Dai", artist: "Shakira", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/dai-dai.mp3" },
    { id: "dandelions", title: "Dandelions", artist: "Ruth B.", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/dandelions.mp3" },
    { id: "demons", title: "Demons", artist: "Imagine Dragons", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/demons.mp3" },
    { id: "end-of-beginning", title: "End of Beginning", artist: "Djo", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/end-of-beginning.mp3" },
    { id: "eva-vintage", title: "Lonely-Lonely", artist: "Eva Vintage", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/eva-vintage.mp3" },
    { id: "fairytale", title: "Fairytale", artist: "Alexander Rybak", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/fairytale.mp3" },
    { id: "freaks", title: "Freaks", artist: "Surf Curse", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/freaks.mp3" },
    { id: "frozen", title: "Frozen", artist: "Madonna", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/frozen.mp3" },
    { id: "frozy-tomo-islands", title: "Frozy Tomo Islands", artist: "Frozy", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/frozy-tomo-islands.mp3" },
    { id: "funk-abnormal", title: "Funk Abnormal", artist: "DJ V12", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/funk-abnormal.mp3" },
    { id: "gandagana", title: "Gandagana", artist: "Chveneburebi", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/gandagana.mp3" },
    { id: "gangstas-paradise", title: "Gangsta's Paradise", artist: "Coolio", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/gangstas-paradise.mp3" },
    { id: "gasolina", title: "Gasolina", artist: "Daddy Yankee", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/gasolina.mp3" },
    { id: "give-it-up-to-me", title: "Give It Up To Me", artist: "Sean Paul", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/Give-It-Up-To-Me.mp3" },
    { id: "golden-brown", title: "Golden Brown", artist: "The Stranglers", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/golden-brown.mp3" },
    { id: "heat-waves", title: "Heat Waves", artist: "Glass Animals", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/heat-waves.mp3" },
    { id: "hips-dont-lie", title: "Hips Don't Lie", artist: "Shakira", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/hips-dont-lie.mp3" },
    { id: "house-of-memories", title: "House of Memories", artist: "Panic! at the Disco", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/house-of-memories.mp3" },
    { id: "hymn-for-the-weekend", title: "Hymn for the Weekend", artist: "Coldplay", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/hymn-for-the-weekend.mp3" },
    { id: "im-good-blue", title: "I'm Good (Blue)", artist: "David Guetta & Bebe Rexha", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/im-good-blue.mp3" },
    { id: "in-the-end", title: "In the End", artist: "Linkin Park", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/in-the-end.mp3" },
    { id: "i-wanna-be-yours", title: "I Wanna Be Yours", artist: "Arctic Monkeys", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/i-wanna-be-yours.mp3" },
    { id: "jaymes-young-infinity", title: "Infinity", artist: "Jaymes Young", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/jaymes-young-infinity.mp3" },
    { id: "let-me-love-you", title: "Let Me Love You", artist: "DJ Snake ft. Justin Bieber", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/let-me-love-you.mp3" },
    { id: "levitating", title: "Levitating", artist: "Dua Lipa", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/levitating.mp3" },
    { id: "love-me-not", title: "Love Me Not", artist: "Ravyn Lenae", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/love-me-not.mp3" },
    { id: "middle-of-the-night", title: "Middle of the Night", artist: "Elley Duhé", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/middle-of-the-night.mp3" },
    { id: "mockingbird", title: "Mockingbird", artist: "Eminem", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/mockingbird.mp3" },
    { id: "no-lie", title: "No Lie", artist: "Sean Paul ft. Dua Lipa", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/no-lie.mp3" },
    { id: "notion", title: "Notion", artist: "The Rare Occasions", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/notion.mp3" },
    { id: "odnogo-slowed", title: "Odnogo (Slowed)", artist: "Unknown", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/odnogo-slowed.mp3" },
    { id: "on-and-on", title: "On and On", artist: "Cartoon", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/on-and-on.mp3" },
    { id: "on-the-floor", title: "On the Floor", artist: "Jennifer Lopez ft. Pitbull", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/on-the-floor.mp3" },
    { id: "poker-face", title: "Poker Face", artist: "Lady Gaga", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/poker-face.mp3" },
    { id: "rasputin", title: "Rasputin", artist: "Boney M.", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/rasputin.mp3" },
    { id: "rock-that-body-slowed-reverb", title: "Rock That Body (Slowed + Reverb)", artist: "The Black Eyed Peas", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/rock-that-body-slowed-reverb.mp3" },
    { id: "runaway", title: "Runaway", artist: "AURORA", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/runaway.mp3" },
    { id: "self-aware", title: "Self Aware", artist: "Unknown", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/self-aware.mp3" },
    { id: "six-days", title: "Six Days", artist: "DJ Shadow", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/six-days.mp3" },
    { id: "somebody-that-i-used-to-know", title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/somebody-that-i-used-to-know.mp3" },
    { id: "stay", title: "Stay", artist: "The Kid LAROI & Justin Bieber", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/stay.mp3" },
    { id: "stereo-hearts", title: "Stereo Hearts", artist: "Gym Class Heroes ft. Adam Levine", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/stereo-hearts.mp3" },
    { id: "sweater-weather", title: "Sweater Weather", artist: "The Neighbourhood", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/sweater-weather.mp3" },
    { id: "the-real-slim-shady", title: "The Real Slim Shady", artist: "Eminem", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/the-real-slim-shady.mp3" },
    { id: "tokyo-drift", title: "Tokyo Drift", artist: "Teriyaki Boyz", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/tokyo-drift.mp3" },
    { id: "until-i-found-you", title: "Until I Found You", artist: "Stephen Sanchez", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/until-i-found-you.mp3" },
    { id: "stan", title: "Stan", artist: "Eminem ft. Dido", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/stan.mp3" },
    { id: "loser", title: "Loser", artist: "Tame Impala", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/loser-tame-impala.mp3" },
    { id: "jamaican", title: "Jamaican", artist: "Unknown", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/jamican.mp3" },
    { id: "attention", title: "Attention", artist: "Charlie Puth", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/attention.mp3" },
    { id: "billie-jean", title: "Billie Jean", artist: "Michael Jackson", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/billie-jean.mp3" },
    { id: "rockabybe", title: "Rockabybe", artist: "Unknown", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/rockabybe.mp3" },
    { id: "without-me", title: "Without Me", artist: "Eminem", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/without-me.mp3" },
    { id: "lonely-lonely", title: "Lonely-lonely", artist: "Unknown", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/lonely-lonely.mp3" },
    { id: "death-bed", title: "death bed (coffee for your head)", artist: "Powfu ft. beabadoobee", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/death-bed.mp3" },
    { id: "night-changes", title: "Night Changes", artist: "One Direction", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/night-changes.mp3" },
    { id: "beat-it", title: "Beat It", artist: "Michael Jackson", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/beat-it.mp3" },
    { id: "they-dont-care", title: "They Don't Care About Us", artist: "Michael Jackson", file: "https://lzwchczsbbzspakwuafx.supabase.co/storage/v1/object/public/music/they-dont-care-about-us.mp3" }
];
